[package]
name = "ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
assets = { path = "../assets" }
render-api = { path = "../render-api" }
semantic-input = { path = "../input" }
sha2.workspace = true
serde = { version = "1", features = ["derive"] }
