(component
  (import "$GAMEPLAY" (instance $gameplay
    (type $v (record (field "x" f32) (field "y" f32) (field "z" f32)))
    (export "vector3" (type $vector3 (eq $v)))
    (type $p (record (field "runtime-id" u64) (field "position" $vector3)))
    (export "player" (type $player (eq $p)))
    (type $s (record (field "session" u64) (field "dimension" s32)
      (field "eye" $vector3) (field "yaw" f32) (field "pitch" f32)
      (field "attack-held" bool) (field "frame-seconds" f32) (field "players" (list $player))))
    (export "snapshot" (type $snapshot (eq $s)))
    (export "read-frame" (func (result (result (option $snapshot) (error string)))))
    (export "cancel-jump" (func (result (result (error string)))))
    (export "pulse-jump" (func (result (result (error string)))))
    (export "set-packet-delay" (func (param "delay-ms" u32) (result (result (error string)))))
    (export "set-show-real-position" (func (param "enabled" bool) (result (result (error string)))))
    (export "rotate" (func (param "yaw-delta" f32) (param "pitch-delta" f32)
      (result (result (error string)))))))
  (alias export $gameplay "read-frame" (func $read-frame))
  (alias export $gameplay "cancel-jump" (func $cancel-jump))
  (alias export $gameplay "pulse-jump" (func $pulse-jump))
  (alias export $gameplay "rotate" (func $rotate))
  (alias export $gameplay "set-packet-delay" (func $packet-delay))
  (alias export $gameplay "set-show-real-position" (func $show-position))
  (core module $memory-module
    (memory (export "memory") 1)
    (global $next (mut i32) (i32.const 4096))
    (func (export "realloc") (param i32 i32 i32 i32) (result i32)
      (local $old i32)
      global.get $next local.tee $old
      local.get 3 i32.add global.set $next local.get $old))
  (core instance $mem (instantiate $memory-module))
  (alias core export $mem "memory" (core memory $memory))
  (alias core export $mem "realloc" (core func $realloc))
  (core func $lower-read (canon lower (func $read-frame) (memory $memory) (realloc $realloc)))
  (core func $lower-rotate (canon lower (func $rotate) (memory $memory) (realloc $realloc)))
  (core func $lower-delay (canon lower (func $packet-delay) (memory $memory) (realloc $realloc)))
  (core func $lower-show (canon lower (func $show-position) (memory $memory) (realloc $realloc)))
  (core func $lower-jump (canon lower (func $pulse-jump) (memory $memory) (realloc $realloc)))
  (core func $lower-cancel-jump (canon lower (func $cancel-jump) (memory $memory) (realloc $realloc)))
  (core module $code
    (import "host" "cancel-jump" (func $cancel-jump (param i32)))
    (import "host" "jump" (func $jump (param i32)))
    (import "host" "read" (func $read (param i32)))
    (import "host" "rotate" (func $rotate (param f32 f32 i32)))
    (import "host" "delay" (func $delay (param i32 i32)))
    (import "host" "show" (func $show (param i32 i32)))
    (import "host" "memory" (memory 1))
    (func (export "init") $INIT)
    (func (export "frame") $FRAME))
  (core instance $host
    (export "cancel-jump" (func $lower-cancel-jump))
    (export "jump" (func $lower-jump))
    (export "read" (func $lower-read))
    (export "rotate" (func $lower-rotate))
    (export "delay" (func $lower-delay))
    (export "show" (func $lower-show))
    (export "memory" (memory $memory)))
  (core instance $run (instantiate $code (with "host" (instance $host))))
  (func (export "init") (canon lift (core func $run "init")))
  (func (export "frame") (canon lift (core func $run "frame"))))
