pub(in crate::chunk) mod arena;
mod authored_upload;
pub(in crate::chunk) mod bind_groups;
pub(in crate::chunk) mod layout;
pub(in crate::chunk) mod resource_geometry;
mod resource_sorts;
pub(in crate::chunk) mod telemetry;
pub(in crate::chunk) mod texture_upload;
pub(in crate::chunk) mod types;
pub(in crate::chunk) mod upload;
